spring.application.name=adventurebook
# H2 Configuration
spring.datasource.url=jdbc:h2:file:/app/data/adventure_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# Hibernate Settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

spring.jackson.deserialization.read-unknown-enum-values-as-null=true
spring.jackson.mapper.accept-case-insensitive-enums=true